{{- if and .Values.mountSecret .Values.secretFiles }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
{{- range $key, $val := .Values.secretFiles }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end }}
